# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "triangolo\ rettangolo.o"
LINKOBJ  = "triangolo rettangolo.o"
LIBS     = -L"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"P:/informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Area Tri-angolo.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"triangolo\ rettangolo.o": triangolo\ rettangolo.c
	$(CC) -c "triangolo rettangolo.c" -o "triangolo rettangolo.o" $(CFLAGS)
