# Project: Matrice lettere
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Matrice\ lettere.o"
LINKOBJ  = "Matrice lettere.o"
LIBS     = -L"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Matrice lettere.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Matrice\ lettere.o": Matrice\ lettere.c
	$(CC) -c "Matrice lettere.c" -o "Matrice lettere.o" $(CFLAGS)
