var plgGdprAllCookiesDisabledByScript=!1,detectedOldIPhone=!1;if(null!==navigator.userAgent.match(/iPhone/i)){var iphone4=480==window.screen.height,iphone5=568==window.screen.height;if(iphone4||iphone5)detectedOldIPhone=!0}
var plgGdprDisableAllCookies=function(b){var f=document.cookie.split("; "),a=["cookieconsent_status"];"undefined"!==typeof gdprJSessCook&&a.push(gdprJSessCook);if(gdprConfigurationOptions.allowedCookies){var c=gdprConfigurationOptions.allowedCookies.split(",");a=a.concat(c)}c=function(a){for(var b=window.location.hostname.split(".");0<b.length;){var c=encodeURIComponent(a.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+b.join(".")+" ;path=",d=location.pathname.split("/");
for(document.cookie=c+"/";0<d.length;){var e=d.join("/");e||(e="/");document.cookie=c+e;d.pop()}b.shift()}};for(var d=0;d<f.length;d++){for(var g=!0,e=0;e<a.length;e++)-1!=f[d].indexOf(a[e])&&(g=!1);g&&c(f[d])}b||!gdprConfigurationOptions.blockCookieDefine||detectedOldIPhone||Object.defineProperty(document,"cookie",{get:function(){return""},set:function(){return!0}});jQuery("*[src*=gdprlock],*[data-source=gdprlock]").remove();plgGdprAllCookiesDisabledByScript=!0};
(function(){if("undefined"!==typeof gdpr_unset_categories_cookies)for(var b=0;b<gdpr_unset_categories_cookies.length;b++)for(var f=gdpr_unset_categories_cookies[b],a=window.location.hostname.split(".");0<a.length;){var c=encodeURIComponent(f.split(";")[0].split("=")[0])+"=; expires=Thu, 01-Jan-1970 00:00:01 GMT; domain="+a.join(".")+" ;path=",d=location.pathname.split("/");for(document.cookie=c+"/";0<d.length;){var g=d.join("/");g||(g="/");document.cookie=c+g;d.pop()}a.shift()}})();
gdprConfigurationOptions.lawByCountry||("opt-in"!=gdprConfigurationOptions.complianceType||localStorage.getItem("hasConsented")||localStorage.getItem("setConsentedCookie")||plgGdprDisableAllCookies(),"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&plgGdprDisableAllCookies());
jQuery(function(b){plgGdprAllCookiesDisabledByScript||jQuery("*[src*=gdprlock],*[data-source=gdprlock]").remove();window.gdprIsCookieConsentPresent=function(a){a=("; "+document.cookie).split("; "+a+"=");return 2!=a.length?void 0:a.pop().split(";").shift()}("cookieconsent_status");var f=function(){gdpr_enable_log_cookie_consent&&b.ajax({type:"POST",url:gdpr_ajax_livesite+"index.php?option=com_gdpr&task=user.processGenericCookieCategories",data:{gdpr_generic_cookie_consent:localStorage.getItem("hasConsented")?
1:0}});var a=b("iframe").length,c=!!navigator.mozGetUserMedia;gdprConfigurationOptions.blockExternalCookiesDomains&&a&&c&&localStorage.setItem("refreshIframeCache",!0);setTimeout(function(){window.location.reload()},0)};b(document).on("click","a.cc-allow",function(a){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("hasDeclined")&&(localStorage.removeItem("hasDeclined"),localStorage.removeItem("hasDenyMessage"),localStorage.removeItem("hasExplititDeclinedAll"),localStorage.setItem("setRevokedCookie",
!0),f())});localStorage.getItem("refreshIframeCache")&&(b("iframe").each(function(a,c){a=b(c).clone();b(c).after(a).remove()}),localStorage.getItem("setConsentedCookie")||localStorage.removeItem("refreshIframeCache"));window.cookieconsent.initialise({type:gdprConfigurationOptions.complianceType,layout:gdprConfigurationOptions.toolbarLayout,theme:gdprConfigurationOptions.toolbarTheme,position:gdprConfigurationOptions.toolbarPosition,revokeposition:gdprConfigurationOptions.revokePosition,container:document.querySelector(gdprConfigurationOptions.containerSelector),
palette:{popup:{background:gdprConfigurationOptions.popupBackground,text:gdprConfigurationOptions.popupText,link:gdprConfigurationOptions.popupLink},button:{background:gdprConfigurationOptions.buttonBackground,border:gdprConfigurationOptions.buttonBorder,text:gdprConfigurationOptions.buttonText},highlight:{background:gdprConfigurationOptions.highlightBackground,border:gdprConfigurationOptions.highlightBorder,text:gdprConfigurationOptions.highlightText},highlightDismiss:{background:gdprConfigurationOptions.highlightDismissBackground,
border:gdprConfigurationOptions.highlightDismissBorder,text:gdprConfigurationOptions.highlightDismissText},highlightOpacity:{opacity:gdprConfigurationOptions.highlightOpacity}},revokable:!!gdprConfigurationOptions.revokable,location:!!gdprConfigurationOptions.lawByCountry,law:{regionalLaw:!gdprConfigurationOptions.lawByCountry},showLink:!!gdprConfigurationOptions.showLinks,static:!gdprConfigurationOptions.toolbarPositionmentType,dismissOnScroll:gdprConfigurationOptions.dismissOnScroll,dismissOnTimeout:gdprConfigurationOptions.dismissOnTimeout,
animateRevokable:!!gdprConfigurationOptions.hideRevokableButton,onInitialise:function(a){"opt-out"==gdprConfigurationOptions.complianceType&&localStorage.getItem("setRevokedCookie")&&(this.setStatus("allow",!0),localStorage.removeItem("setRevokedCookie"),f())},content:{header:gdprConfigurationOptions.headerText,message:gdprConfigurationOptions.messageText,dismiss:gdprConfigurationOptions.dismissText,allow:gdprConfigurationOptions.allowText,deny:gdprConfigurationOptions.denyText,link:gdprConfigurationOptions.cookiePolicyLinkText,
href:gdprConfigurationOptions.cookiePolicyLink,privacylink:gdprConfigurationOptions.privacyPolicyLinkText,privacyhref:gdprConfigurationOptions.privacyPolicyLink},onStatusChange:function(a,c){c=this.options.type;var d=this.hasConsented();if("opt-in"==c&&(d||b("a.cc-btn",this.element).hasClass("cc-allow"))&&"allow"==a){var g=localStorage.getItem("hasConsented"),e={hasConsented:!0,timestamp:(new Date).getTime()};localStorage.setItem("hasConsented",JSON.stringify(e));plgGdprAllCookiesDisabledByScript&&
localStorage.setItem("setConsentedCookie",!0);localStorage.removeItem("hasExplititDeclinedAll");b("input.cc-cookie-checkbox").attr("disabled",!1);g&&gdprIsCookieConsentPresent||f()}"opt-in"!=c||d&&!b("a.cc-btn",this.element).hasClass("cc-deny")||"deny"!=a||(g=localStorage.getItem("hasConsented"),localStorage.removeItem("hasConsented"),localStorage.removeItem("setConsentedCookie"),e={hasDeclined:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasFirstDeclined",JSON.stringify(e)),localStorage.setItem("hasExplititDeclinedAll",
JSON.stringify(e)),this.setStatus("deny",!0),b("input.cc-cookie-checkbox").attr("disabled",!0),g&&f());"opt-out"!=c||d||localStorage.getItem("hasDeclined")||(plgGdprDisableAllCookies(!0),e={hasDeclined:!0,timestamp:(new Date).getTime()},localStorage.setItem("hasDeclined",JSON.stringify(e)),localStorage.setItem("hasFirstDeclined",JSON.stringify(e)),localStorage.setItem("hasExplititDeclinedAll",JSON.stringify(e)),b("input.cc-cookie-checkbox").attr("disabled",!0),f());gdprConfigurationOptions.denyMessageEnabled&&
"allow"==a&&localStorage.removeItem("hasDenyMessage")},onPopupOpen:function(a){"opt-in"!=gdprConfigurationOptions.complianceType||!gdprConfigurationOptions.autoAcceptOnNextPage||a||localStorage.getItem("hasExplititDeclinedAll")||(a=localStorage.getItem("autoActivateOnNextPage"),2==parseInt(a)?(b("div.cc-window.cc-banner").hide(),localStorage.setItem("autoActivateOnNextPage",1),b("a.cc-btn.cc-allow").trigger("click")):a||localStorage.setItem("autoActivateOnNextPage",2))}})});
