# Project: Palla che rimbalza
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Palla.o
LINKOBJ  = Palla.o
LIBS     = -L"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Palla che rimbalza.exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Palla.o: Palla.cpp
	$(CPP) -c Palla.cpp -o Palla.o $(CXXFLAGS)
