# Project: SUDOKU
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = SUDOKU.o
LINKOBJ  = SUDOKU.o
LIBS     = -L"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Bonafe Pezzano/Informatica/DEV/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = SUDOKU.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

SUDOKU.o: SUDOKU.cpp
	$(CPP) -c SUDOKU.cpp -o SUDOKU.o $(CXXFLAGS)
