# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "Molto\ Casuale.o"
LINKOBJ  = "Molto Casuale.o"
LIBS     = -L"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib" -L"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pg
INCS     = -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"K:/Bonafe Pezzano/Informatica/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Molto Casuale.exe"
CXXFLAGS = $(CXXINCS) -pg
CFLAGS   = $(INCS) -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"Molto\ Casuale.o": Molto\ Casuale.c
	$(CC) -c "Molto Casuale.c" -o "Molto Casuale.o" $(CFLAGS)
