# Project: VERIFICA2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = VERIFICA2.o
LINKOBJ  = VERIFICA2.o
LIBS     = -L"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib" -L"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"K:/Bonafe Pezzano/Informatica/OrwellDev-CppPortable/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = VERIFICA2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

VERIFICA2.o: VERIFICA2.c
	$(CC) -c VERIFICA2.c -o VERIFICA2.o $(CFLAGS)
