# Project: bandiera olimpica
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = bandiera.o
LINKOBJ  = bandiera.o
LIBS     = -L"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi -lgdi32 -luser32 -m32
INCS     = -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/include" -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"K:/Bonafe Pezzano/Informatica/Esercizi/Grafica/OrwellDev-CppPortable_grafica/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = bandiera.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

bandiera.o: bandiera.cpp
	$(CPP) -c bandiera.cpp -o bandiera.o $(CXXFLAGS)
