(function(d){if(d.MRWccsa)return d.MRWccsa;var c=d.document,l="textContent"in c.body,k=function(){function k(a,b){var m=c.createElement(a);m.innerHTML=b;return m}function n(a){var b=c.createDocumentFragment();b.appendChild(a);c.body.appendChild(b.cloneNode(!0))}function p(){var a=0;"number"==typeof d.pageYOffset?a=d.pageYOffset:c.body&&c.body.scrollTop?a=c.body.scrollTop:c.documentElement&&c.documentElement.scrollTop&&(a=c.documentElement.scrollTop);return a}function f(a,b,c){a.addEventListener?a.addEventListener(b,
c,!1):a.attachEvent?("DOMContentLoaded"==b&&(b="readystatechange"),a.attachEvent("on"+b,c)):("DOMContentLoaded"==b&&(b="load"),a["on"+b]=c)}function q(a){var b=c.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a;c.getElementsByTagName("head")[0].appendChild(b)}function r(){var a=!0;$('link[rel="stylesheet"]').each(function(){var b=$(this).prop("href");if(-1!=b.indexOf("Open+Sans")&&-1!=b.indexOf("Francois+One"))return a=!1});a&&q("//fonts.googleapis.com/css?family=Open+Sans%7CFrancois+One");
q("//www.mrwebmaster.it/v6_css/mrw.ccsa.min.css")}function C(){var a=c.createElement("div");a.appendChild(k("span","Su questo sito utilizziamo cookie, di prima e di terza parte, per finalit&agrave; tecniche e, previo tuo consenso, di profilazione, al fine di proporti annunci pubblicitari in linea con le tue preferenze. <strong>Per maggiori informazioni o per prestare il consenso solo ad alcuni utilizzi, leggi l'informativa</strong>. Chiudendo questo avviso, proseguendo nella navigazione, effettuando lo scroll della pagina o altro tipo di interazione col sito, acconsenti all'utilizzo di tutti i cookie."));
a.appendChild(D());a.appendChild(E());var b=c.createElement("div");b.id="cookie-consent";b.appendChild(a);return b}function E(){var a=c.createElement("a");a.id="cookie-consent-dismiss";a.className="dismiss";a.href="#";l?a.textContent="OK":a.innerText="OK";return a}function D(){var a=c.createElement("a");a.id="cookie-consent-policy";a.className="policy";a.href="https://www.mrwebmaster.it/info/cookie.html";a.target="_blank";l?a.textContent="leggi informativa":a.innerText="leggi informativa";return a}
function t(){var a=c.getElementById("cookie-consent");null!=a&&a.parentNode.removeChild(a);a=u;d.removeEventListener?d.removeEventListener("scroll",a,!1):d.detachEvent?d.detachEvent("onscroll",a):d.onscroll=null}function v(){var a=new Date;a.setFullYear(a.getFullYear()+1);a="cookie_consent=all; expires="+a.toGMTString()+"; path=/; domain=";var b=location.hostname,d=b.split("."),e=d.length;c.cookie=a+(2==e?b:d[e-2]+"."+d[e-1])}function w(){v();x?d.location.reload():(t(),g())}function u(){p()>=y+50&&
w()}function F(a,b){a&&(x=!0);b&&(z=!0);c.cookie.match(/cookie_consent=([^;]+)/)?g():(t(),r(),n(C()),c.getElementById("cookie-consent-dismiss").onclick=w,y=p(),f(d,"scroll",u),f(d,"load",function(){for(var a=c.getElementsByTagName("a"),b=0;b<a.length;b++)"cookie-consent-policy"!=a[b].id&&f(a[b],"click",v)}))}function h(a){(new Image).src="//www.mrwebmaster.it/ccsa.php?do="+a+"&x="+Date.now()}function G(){var a=c.createElement("button");a.id="stop-ab-btn";a.innerHTML="Ho disattivato il blocco <span>della pubblicit&agrave;</span>";
return a}function H(){h("adbclk");d.location.reload()}function I(){var a=c.createElement("div");a.setAttribute("class","pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links");a.setAttribute("style","width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -1000px !important;");e=d.document.body.appendChild(a);e.offsetParent;e.offsetHeight;e.offsetLeft;e.offsetTop;e.offsetWidth;e.clientHeight;e.clientWidth}function J(){var a=
!1;if(null!==d.document.body.getAttribute("abp")||null===e.offsetParent||0==e.offsetHeight||0==e.offsetLeft||0==e.offsetTop||0==e.offsetWidth||0==e.clientHeight||0==e.clientWidth)a=!0;else if(void 0!==d.getComputedStyle){var b=d.getComputedStyle(e,null);!b||"none"!=b.getPropertyValue("display")&&"hidden"!=b.getPropertyValue("visibility")||(a=!0)}null!==e&&(d.document.body.removeChild(e),e=null);return a}function A(){if(z){r();var a=c.body,b=a.className.concat(" stop-ab");a.className=b;a=c.createElement("div");
a.innerHTML='<img class="stop-ab-img" src="//www.mrwebmaster.it/v6_img/stop_ab.png"><strong class="stop-ab-titolo">Disabilita il blocco della pubblicit&agrave;</strong><p>Gli <span>annunci pubblicitari</span> presenti nel nostro sito sono <span>sicuri al 100%</span> e <span>non sono invasivi</span>... Perch&egrave; vuoi bloccarli? <span>Senza la pubblicit&agrave; questo sito non potrebbe esistere</span>. Per proseguire ti invitiamo a <strong>disabilitare il tuo Ad Blocker</strong> o ad <strong>inserire Mr. Webmaster in White List</strong>.</p>';
a.appendChild(G());b=c.createElement("div");b.id="stop-ab";b.appendChild(a);n(b);c.getElementById("stop-ab-btn").onclick=H}h("adbpgv")}function B(a,b){var d=c.cookie.match(/cookie_consent=strict/);a&&(d&&googletag.pubads().setRequestNonPersonalizedAds(1),googletag.pubads().refresh());b&&(d&&(adsbygoogle.requestNonPersonalizedAds=1),adsbygoogle.pauseAdRequests=0);d&&h("strpgv")}function g(){I();if(J())A();else{var a="undefined"!==typeof googletag?!0:!1,b="undefined"!==typeof adsbygoogle?!0:!1;if(a||
b)if(a&&googletag.apiReady)B(!0,b);else{var e=c.createElement("script");e.src="//www.mrwebmaster.it/adserver/adview.js?adzone=top&adsize=300x250&type=banner&slot="+parseInt(1E8*Math.random());e.onerror=function(){A();d.document.body.removeChild(e)};e.onload=function(){B(a,b);d.document.body.removeChild(e)};c.body.appendChild(e)}else return!1}}var e=null,z=!1,x=!1,y=0;return{cookieConsent:function(a,b){f(c,"DOMContentLoaded",function(c){F(a,b)})},showAds:function(){f(c,"DOMContentLoaded",function(a){g()})}}}();
return d.MRWccsa=k})(this);
