var $win=$(window),mrw_host="https://www.mrwebmaster.it";
$(function(){$.getScript(mrw_host+"/v6_lib/noty/packaged/jquery.noty.packaged.min.js");$(".lista-cliccabile > li, .cliccabile").click(function(a){a.preventDefault();a=$(this).find("a").attr("href");location.href=a});$(".mrw-auth-opener").click(function(){var a=$(this).data("regurl"),b=$(this).data("backurl"),c=$(this).data("avviso");mrw_auth_popup(a,b,c)});$("body").on("click",".mrw-custom-share-btn > li",function(){var a=$(this).parent(),b=a.data("lnk"),c=a.data("tit"),d=!1;if($(this).hasClass("fb"))d=
"fb";else if($(this).hasClass("tw"))d="tw";else if($(this).hasClass("gp"))d="gp";else if($(this).hasClass("ln"))d="ln";else return;var e="",f=400;if("fb"==d){if(window.FB){FB.ui({method:"feed",link:b},function(a){});return}e="https://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(b)}else if("tw"==d)e="https://twitter.com/intent/tweet?text="+encodeURIComponent(c)+"&url="+encodeURIComponent(b),f=430;else if("gp"==d)e="https://plus.google.com/share?url="+encodeURIComponent(b),f=600;else if("ln"==
d)e="http://www.linkedin.com/shareArticle?mini=true&url="+encodeURIComponent(b)+"&title="+encodeURIComponent(c),f=570;else return;c=f;f=($win.width()-600)/2;var g=($win.height()-c)/2,h=window.open(e,"social","status=1,width=600,height="+c+",top="+g+",left="+f);if(a.is("#mrw-social-ajax"))var k=setInterval(function(){if(h.closed){clearInterval(k);var a=0;$.post("/ajax.php",{"do":"sharecnt",pageurl:b,social:d},function(c){1==c.success&&(a=c.output,a>cnt&&track_sociale(d,b),$("#scl"+d).data("cnt",a).children("span").text(a))},
"json")}},1E3)});$("#sticky-footer li").click(function(){if($(this).hasClass("sf-s")||$(this).hasClass("sf-n")){var a=$("#sticky-footer-popup"),b=$win.outerHeight();a.css("min-height",b).show().children(".tutto-bianco-x").click(function(){a.hide();a.children(".sf-pp-share").hide();a.children(".sf-pp-signup").hide()});$(this).hasClass("sf-s")?a.children(".sf-pp-share").fadeIn():a.children(".sf-pp-signup").fadeIn()}else $("html, body").animate({scrollTop:$("#commenti").offset().top-60},1E3)});mrw_menu_network();
$(document).on("click",'a[href^="#"]',function(a){a.preventDefault();a=0;var b=$.attr(this,"href").substr(1);$("#"+b).length?a=$("#"+b).offset().top:$('[name="'+b+'"]').length&&(a=$('[name="'+b+'"]').offset().top);goto_y(a)})});function goto_y(a,b){b=b||800;0<a&&(a=$("#postbar").length&&$("#postbar").is(":visible")?a-120:a-60);$("html, body").animate({scrollTop:a},b)}function goto_id(a){goto_y($("#"+a).offset().top)}function scroll_top(){goto_y(0,400)}
function crea_cookie(a,b,c){if(c){var d=new Date;d.setTime(d.getTime()+864E5*c);c="; expires="+d.toGMTString()}else c="";document.cookie=escape(a)+"="+escape(b)+c+"; domain=.mrwebmaster.it; path=/"}function leggi_cookie(a){a=escape(a)+"=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return unescape(d.substring(a.length,d.length))}return null}
function mrw_errore(a){noty({theme:"relax",type:"error",layout:"bottomRight",text:a,timeout:4E3})}function mrw_successo(a){noty({theme:"relax",type:"success",layout:"bottomRight",text:a,timeout:4E3})}
function mrw_layer(a,b,c){var d=!0;$win.width()<b?(b="100%",c=$win.height()+"px",d=!1):(parseInt(($win.height()-c)/2),parseInt(($win.width()-b)/2),b+="px",c+="px");$("body").css({height:"100%",overflow:"hidden"});if(!$("#mrw-layer-css").length){var e=mrw_host+"/v6_css/mrw.layer.min.css";$("head").append('<link id="mrw-layer-css" rel="stylesheet" type="text/css" href="'+e+'" media="all"/>')}b='<div id="mrw-layer" style="display:none;" '+(d?"":'class="mrw-layer-mobile"')+'>  <span class="mrw-layer-close" onclick="mrw_layer_close();"><i class="icon-cancel"></i></span>  <div class="mrw-layer-inner" style="width:'+
b+';">    <iframe src="'+a+'" style="width:'+b+";height:"+c+';"></iframe>  </div></div>';$("body").append(b);setTimeout(function(){$("#mrw-layer").fadeIn();d&&"/"==a.charAt(0)&&mrw_layer_adjust();$(document).keyup(mrw_layer_esc)},50)}function mrw_layer_esc(a){27==a.keyCode&&mrw_layer_close()}function mrw_layer_close(){$("#mrw-layer").remove();$(document).unbind("keyup",mrw_layer_esc);$("body").css({height:"auto",overflow:"scroll"})}
function mrw_layer_adjust(){var a=$("#mrw-layer iframe"),b=0,c=0,d=setInterval(function(){a.length?a.load(function(){c=a.contents().find("body").height()+1;c!=b&&(a.css("height",c+"px"),b=c)}):window.clearInterval(d)},300)}
function mrw_menu_network(){var a='<div class="sub-netw-head"><img class="sub-netw-logo" src="'+mrw_host+'/v6_img/netw_logo_3x.png" alt="Mr.Webmaster"/><img class="sub-netw-netw" src="'+mrw_host+'/v6_img/netw_netw_3x.png" alt="MRW Network"/></div><div class="sub-netw-cont"><ul><li><a href="'+mrw_host+'/"><i class="icon-home"></i> Home</a></li><li><a href="'+mrw_host+'/didattica/"><i class="icon-book"></i> Didattica</a></li><li><a href="'+mrw_host+'/download/"><i class="icon-download-alt"></i> Download</a></li><li><a href="'+
mrw_host+'/risorse/"><i class="icon-th"></i> Risorse</a></li><li><a href="'+mrw_host+'/news/"><i class="icon-newspaper"></i> News</a></li><li><a href="http://blog.mrwebmaster.it/"><i class="icon-users"></i> Blog</a></li><li><a href="http://forum.mrwebmaster.it/"><i class="icon-chat"></i> Forum</a></li></ul><ul><li><a href="http://toolset.mrwebmaster.it/"><i class="icon-wrench"></i> Toolset.it</a></li><li><a href="http://sitemarket.mrwebmaster.it/"><i class="icon-basket"></i> SiteMarket.it</a></li><li><a href="http://www.mrwebmaster.it/codalo/"><i class="icon-code"></i> Codalo.it</a></li></ul></div>',
b=$("#sub-netw");b.length&&b.append(a)}
function mrw_newsletter_signup(a,b){var c='<div id="nl-signup"><div class="no-h2">'+b+'</div><p id="nl-signup-err">Iscriviti alla nostra newsletter e ricevi gli ultimi aggiornamenti dal nostro network.</p><form id="nl-signup-frm" method="post" action="'+mrw_host+'/utenti/reg-email.html"><input type="hidden" name="exe" value="1"><div class="nl-signup-cols"><div><input type="text" class="maxi" name="email" placeholder="Inserisci la tua mail"></div><div><button class="maxi" type="submit">ISCRIVITI</button></div></div><p class="cb cb-small"><input type="checkbox" id="nl-signup-legal" name="privacy" value="1"><label for="nl-signup-legal"></label> Ho letto, compreso ed accettato quanto indicato nell\'<a href="https://www.mrwebmaster.it/info/privacy.html" target="_blank" rel="nofollow">informativa sulla privacy</a> ed acconsento a ricevere comunicazioni a carattere informativo e/o commerciale tramite posta elettronica</p></form></div>';$(a).after(c);
$("#nl-signup-frm").submit(function(){if(!$("#nl-signup-legal").is(":checked"))return $("#nl-signup-err").html('<span style="color:#CC3300"><i class="icon-warning-empty"></i> Devi accettare il trattamento dei dati personali</span>'),!1})}
function mrw_sticky_footer(a,b){var c='<div id="sticky-footer"><ul><li class="sf-s"><i class="icon-export"></i></li><li class="sf-n"><i class="icon-mail"></i></li><li class="sf-c"><i class="icon-pencil"></i></li></ul></div><div id="sticky-footer-popup" class="tutto-bianco"><div class="tutto-bianco-x"><i class="icon-cancel"></i></div><div class="sf-pp-share"><div class="sf-pp-share-titolo">Condividi</div><ul class="sf-pp-share-social mrw-custom-share-btn" data-tit="'+a+'" data-lnk="'+b+'"><li class="fb"><i class="icon-facebook"></i></li><li class="tw"><i class="icon-twitter"></i></li><li class="gp"><i class="icon-gplus"></i></li><li class="ln"><i class="icon-linkedin"></i></li></ul></div><div class="sf-pp-signup"><div class="sf-pp-signup-titolo"><span>Ti &egrave; sembrato<br/>interessante?</span><span id="sf-pp-signup-err">...Iscriviti alla newsletter!</span></div><form id="sf-pp-signup-frm" method="post" action="'+
mrw_host+'/utenti/reg-email.html"><input type="hidden" name="exe" value="1"><input type="text" class="maxi" name="email" placeholder="Inserisci la tua mail"><button class="maxi" type="submit">ISCRIVITI</button><p class="cb cb-small"><input type="checkbox" id="sf-pp-signup-legal" name="privacy" value="1"><label for="sf-pp-signup-legal"></label> Ho letto, compreso ed accettato quanto indicato nell\'<a href="https://www.mrwebmaster.it/info/privacy.html" target="_blank" rel="nofollow">informativa sulla privacy</a> ed acconsento a ricevere comunicazioni a carattere informativo e/o commerciale tramite posta elettronica</p></form></div></div>';
$("body").append(c);$("#sf-pp-signup-frm").submit(function(){if(!$("#sf-pp-signup-legal").is(":checked"))return $("#sf-pp-signup-err").html('<span style="color:#CC3300"><i class="icon-warning-empty"></i> Devi accettare il trattamento dei dati personali</span>'),!1})}
function mrw_auth_popup(a,b,c){a=a?a:"https://www.mrwebmaster.it/utenti/reg-account.html";var d="https://www.mrwebmaster.it/utenti/resetta-pwd.html";b&&(a+="?backurl="+encodeURIComponent(b),d+="?backurl="+encodeURIComponent(b));b='<div id="modal-auth-popup" class="tutto-bianco"><div class="tutto-bianco-x"><i class="icon-cancel" onclick="$(\'#modal-auth-popup\').hide();"></i></div><div class="ma-container ma-tbl">'+(c?'<div class="ma-info alert info">'+c+'</div><div class="ma-tbl">':"")+'<div class="ma-row"><div class="ma-sx"><form method="post" action="https://www.mrwebmaster.it/utenti/login.html"><input type="hidden" name="exe" value="1">'+
(b?'<input type="hidden" name="backurl" value="'+encodeURIComponent(b)+'">':"")+'<input type="text" name="eml_usr" class="maxi" placeholder="Username o Email"><input type="password" name="pwd" class="maxi" placeholder="Password"><button class="maxi">LOGIN</button><p class="cb cb-small"><input type="checkbox" id="ricordami" name="ricordami" value="1"><label for="ricordami"></label> Ricorda i miei dati per i futuri accessi</p></form></div><div class="ma-dx"><p><strong>Se non sei ancora iscritto, puoi farlo subito</strong>. La registrazione &egrave; gratuita e richiede meno di 2 minuti del tuo tempo!</p><button class="maxi" onclick="location.href=\''+
a+'\'">REGISTRATI GRATIS</button><p class="mbot0">Se sei gi&agrave; iscritto ma hai dimenticato la password <a href="'+d+'">clicca qui</a>.</p></div></div>'+(c?"</div>":"");"NaN</div>";$("#modal-auth-popup").length||$("body").append(b);$("#modal-auth-popup").fadeIn()};
