(function(d){"function"===typeof define&&define.amd?define(["jquery"],d):"object"===typeof module&&module.exports?module.exports=d(require("jquery")):d(jQuery)})(function(d){var u=Array.prototype.slice,v=Array.prototype.splice,p={topSpacing:0,bottomSpacing:0,className:"is-sticky",wrapperClassName:"sticky-wrapper",center:!1,getWidthFrom:"",widthFromWrapper:!0,responsiveWidth:!1,zIndex:"999"},h=d(window),r=d(document),k=[],n=h.height(),m=function(){var b=h.scrollTop(),f=r.height(),c=f-n;c=b>c?c-b:0;
for(var e=0,g=k.length;e<g;e++){var a=k[e],l=a.stickyWrapper.offset().top-a.topSpacing-c;a.stickyWrapper.css("height",a.stickyElement.outerHeight());if(b<=l)null!==a.currentTop&&(a.stickyElement.css({width:"",position:"",top:"","z-index":""}),a.stickyElement.removeClass(a.className),a.stickyElement.trigger("sticky-end",[a]),a.currentTop=null);else{l=f-a.stickyElement.outerHeight()-a.topSpacing-a.bottomSpacing-b-c;l=0>l?l+a.topSpacing:a.topSpacing;if(a.currentTop!==l){var w;a.getWidthFrom?w=d(a.getWidthFrom).width()||
null:a.widthFromWrapper&&(w=a.stickyWrapper.width());null==w&&(w=a.stickyElement.width());a.stickyElement.css("width",w).css("position","fixed").css("top",l).css("z-index",a.zIndex);a.stickyElement.addClass(a.className);null===a.currentTop?a.stickyElement.trigger("sticky-start",[a]):a.stickyElement.trigger("sticky-update",[a]);a.currentTop===a.topSpacing&&a.currentTop>l||null===a.currentTop&&l<a.topSpacing?a.stickyElement.trigger("sticky-bottom-reached",[a]):null!==a.currentTop&&l===a.topSpacing&&
a.currentTop<l&&a.stickyElement.trigger("sticky-bottom-unreached",[a]);a.currentTop=l}var m=a.stickyWrapper.parent();a.stickyElement.offset().top+a.stickyElement.outerHeight()>=m.offset().top+m.outerHeight()&&a.stickyElement.offset().top<=a.topSpacing?a.stickyElement.css("position","absolute").css("top","").css("bottom",0).css("z-index",""):a.stickyElement.css("position","fixed").css("top",l).css("bottom","").css("z-index",a.zIndex)}}},q=function(){n=h.height();for(var b=0,f=k.length;b<f;b++){var c=
k[b],e=null;c.getWidthFrom?c.responsiveWidth&&(e=d(c.getWidthFrom).width()):c.widthFromWrapper&&(e=c.stickyWrapper.width());null!=e&&c.stickyElement.css("width",e)}},g={init:function(b){return this.each(function(){var f=d.extend({},p,b),c=d(this),e=c.attr("id"),h=e?e+"-"+p.wrapperClassName:p.wrapperClassName,a=d("<div></div>").attr("id",h).addClass(f.wrapperClassName);c.wrapAll(function(){if(0==d(this).parent("#"+h).length)return a});e=c.parent();f.center&&e.css({width:c.outerWidth(),marginLeft:"auto",
marginRight:"auto"});"right"===c.css("float")&&c.css({"float":"none"}).parent().css({"float":"right"});f.stickyElement=c;f.stickyWrapper=e;f.currentTop=null;k.push(f);g.setWrapperHeight(this);g.setupChangeListeners(this)})},setWrapperHeight:function(b){b=d(b);var f=b.parent();f&&f.css("height",b.outerHeight())},setupChangeListeners:function(b){window.MutationObserver?(new window.MutationObserver(function(f){(f[0].addedNodes.length||f[0].removedNodes.length)&&g.setWrapperHeight(b)})).observe(b,{subtree:!0,
childList:!0}):window.addEventListener?(b.addEventListener("DOMNodeInserted",function(){g.setWrapperHeight(b)},!1),b.addEventListener("DOMNodeRemoved",function(){g.setWrapperHeight(b)},!1)):window.attachEvent&&(b.attachEvent("onDOMNodeInserted",function(){g.setWrapperHeight(b)}),b.attachEvent("onDOMNodeRemoved",function(){g.setWrapperHeight(b)}))},update:m,unstick:function(b){return this.each(function(){for(var b=d(this),c=-1,e=k.length;0<e--;)k[e].stickyElement.get(0)===this&&(v.call(k,e,1),c=e);
-1!==c&&(b.unwrap(),b.css({width:"",position:"",top:"","float":"","z-index":""}))})}};window.addEventListener?(window.addEventListener("scroll",m,!1),window.addEventListener("resize",q,!1)):window.attachEvent&&(window.attachEvent("onscroll",m),window.attachEvent("onresize",q));d.fn.sticky=function(b){if(g[b])return g[b].apply(this,u.call(arguments,1));if("object"!==typeof b&&b)d.error("Method "+b+" does not exist on jQuery.sticky");else return g.init.apply(this,arguments)};d.fn.unstick=function(b){if(g[b])return g[b].apply(this,
u.call(arguments,1));if("object"!==typeof b&&b)d.error("Method "+b+" does not exist on jQuery.sticky");else return g.unstick.apply(this,arguments)};d(function(){setTimeout(m,1)})});
$(function(){var d=$(window),u=$("#root"),v=$("#navbar"),p=$("#menu-opener"),h=$("#menu"),r=$("#postbar"),k=$("#colonna-fix"),n=$("#menu li.apri-sub"),m=$("#sub-mega"),q=$("#sub-netw"),g=u.hasClass("sticky-nav")?!0:!1,b=g?v.outerHeight():0,f=!1;$("body").bind("touchstart",function(){f=!0});g&&v.sticky({className:"sticky",responsiveWidth:!0,zIndex:99999});p.click(function(){"/v6_img/menu.png"==$(this).attr("src")||"https://www.mrwebmaster.it/v6_img/menu.png"==$(this).attr("src")?($(this).attr("src",
"https://www.mrwebmaster.it/v6_img/menu_chiudi.png"),h.show()):($(this).attr("src","https://www.mrwebmaster.it/v6_img/menu.png"),h.hide())});var c=win_h=mobmenu_h=0,e="",t="";d.resize(function(){c=d.width();win_h=d.height();t=1024<=c?"desktop":"mobile";var a=f?"click":"mouseenter mouseleave";u.css("min-height",win_h+"px");if(e!=t&&"desktop"==t){e="desktop";"/v6_img/menu_chiudi.png"!=p.attr("src")&&"https://www.mrwebmaster.it/v6_img/menu_chiudi.png"!=p.attr("src")||p.attr("src","https://www.mrwebmaster.it/v6_img/menu.png");
h.is(":hidden")&&h.show();$("#menu .sub-menu:visible").hide();h.hasClass("scrollable")&&h.removeClass("scrollable").css("max-height","");n.length&&(n.find("span.up").attr("class","down"),n.children("a").off("click"),n.on(a,function(a){var b=$(".sub-menu",this);f?b.is(":hidden")?b.show():b.hide():"mouseenter"==a.type?b.show():b.hide()}));m.length&&setTimeout(function(){var a=m.parent("li").offset().left,b=v.offset().left+19;m.css("left",-1*(a-b))},500);if(q.length)d.on("load resize",function(){ultimobt_w=
$("#menu > li:last").width();q.css("right",-1*ultimobt_w)});r.length&&(r.sticky({className:"sticky ombra-sotto",topSpacing:b}),$("#postbar .nav > li").hover(function(){$("span",this).show()},function(){$("span",this).hide()}));if(k.length)k.sticky({topSpacing:b+15,bottomSpacing:121}).on("sticky-start",function(){}).on("sticky-end",function(){});$(".touch-ready > li").off("click")}else e!=t&&"mobile"==t&&(e="mobile",mobmenu_h=win_h-b,h.addClass("scrollable").css("max-height",mobmenu_h+"px"),h.is(":visible")&&
h.hide(),n.length&&(n.off(a),n.children("a").click(function(a){a.preventDefault();a=$("span",this);var b=$(this).parent().children(".sub-menu");a.hasClass("down")?(a.attr("class","up"),b.show()):(a.attr("class","down"),b.hide())})),m.length&&m.css("left","auto"),q.length&&q.css("right","auto"),r.length&&r.unstick(),k.length&&k.unstick(),$(".touch-ready > li").click(function(a){a.preventDefault();a=$("h3 > a",this).length?$("h3 > a",this).attr("href"):$("a",this).attr("href");location.href=a}))}).trigger("resize");
$("#menu .sub-menu a").click(function(){var a=$(this).closest(".apri-sub");"mobile"==t?(a.children("a").trigger("click"),p.click()):a.trigger(f?"click":"mouseleave")})});
